name: 'SARIF Issue Manager'
description: 'A GitHub Action to create and manage issues based on SARIF output using GitHub CLI.'
author: 'Yassir Oulmokhtar <yassir.oulmokhtar@karlsgate.com>'
inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true
  sarif-file:
    description: 'Path to the SARIF file'
    required: true
  image-name:
    description: 'Docker image name'
    required: true
  project:
    description: 'Project name for labeling'
    required: false
    default: ''
  allow-reopening:
    description: 'Allow reopening of previously closed issues'
    required: false
    default: true
  allow-closing:
    description: 'Allow closing of resolved issues'
    required: false
    default: true
  cleanup:
    description: 'Removes github issues. This is for testing purposes only.'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
    - ${{ inputs.sarif-file }}
    - ${{ inputs.image-name }}
    - ${{ inputs.project }}
    - ${{ inputs.allow-reopening }}
    - ${{ inputs.allow-closing }}
    - ${{ inputs.cleanup }}